id = "sl4y-theme"
name = "Sl4y Theme"
version = "0.0.1"
schema_version = 1
authors = ["Berkant Ay <berkantay.5@gmail.com>"]
description = "A vomit like high contrast theme for Zed"
repository = "https://github.com/berkantay/zed-theme-sl4y"
